# utils.py
import os
import sys

def resource_path(relative_path):
    """ Get the absolute path to a resource, works for dev and for PyInstaller, only works for ungenerated content"""
    # Asset packed inside the .exe before compiling: Use resource_path("icon.png")

    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

def get_save_path(filename, foldername):
    """works on a local computer as well as on a network drive"""
    # File generated by the app while it is running: Use get_save_path("barcode.png") (for both saving and reading it back later!)
    
    # exist_ok=True mean if folder already exist it will not raise an error. 
    # if exist_ok=False (the default), it will raise an error if the folder already exist.
    # os.makedirs mean make directory
    os.makedirs(foldername, exist_ok=True)  
    # os.path.join mean join the foldername and filename to create a full path
    return os.path.join(foldername, filename)